development:
  adapter: postgresql
  encoding: unicode
  database: veche
  pool: 5
  username: veche
  password:
  host: 10.0.0.2
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: veche-test
  pool: 5
  username: veche
  password:
  host: 10.0.0.2
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: veche
  pool: 5
  username:
  password:
  host:
